In [1]:
import re
import pandas as pd
import random
import numpy as np

filename = "C:\\Users\\mustafa\\Documents\\test.txt"
filename2 = "C:\\Users\\mustafa\\Documents\\test2.txt"

filenames = [filename, filename2]

In [2]:
def extract_all_shingles(filenames):
    
    k4_dict = {}
    k5_dict = {}
    k8_dict = {}
    
    for filename in filenames:
        
        file = open(filename, "r") 
        text = file.read()
        text = re.sub('[^0-9a-zA-Z]+', ' ', text)
        text = re.sub('  ', ' ', text)
        text = text.lower()

        for i in range(len(text)):
            k4 = text[i : i+4]
            k5 = text[i : i+5]
            k8 = text[i : i+8]

            if k4 not in k4_dict:
                k4_dict[k4] = 0
            if k5 not in k5_dict:
                k5_dict[k5] = 0
            if k8 not in k8_dict:
                k8_dict[k8] = 0

    return k4_dict, k5_dict, k8_dict   

    
def shingle(filename, k4_dict, k5_dict, k8_dict):
      
    k4_dict1 = k4_dict.copy()
    k5_dict1 = k5_dict.copy()
    k8_dict1 = k8_dict.copy()
                
    file = open(filename, "r") 
    text = file.read()
    text = re.sub('[^0-9a-zA-Z]+', ' ', text)
    text = re.sub('  ', ' ', text)
    text = text.lower()

    for i in range(len(text)):
        k4 = text[i : i+4]
        k5 = text[i : i+5]
        k8 = text[i : i+8]

        if k4 in k4_dict1:
            k4_dict1[k4] = 1
        if k5 in k5_dict1:
            k5_dict1[k5] = 1
        if k8 in k8_dict1:
            k8_dict1[k8] = 1

    return k4_dict1, k5_dict1, k8_dict1     


def jaccard(x,y):
    counter = 0
    for key in x:
        if x[key] == 1 and y[key] == 1:
            counter = counter + 1      
    return (counter / len(x))      
            
    
def hash(a):
    def sub_hash(x, m = 991):
        return (a*x + 1) % m 
    return sub_hash

In [3]:
k4_dict, k5_dict, k8_dict = extract_all_shingles(filenames)
k4_dict1, k5_dict1, k8_dict1 = shingle(filename, k4_dict, k5_dict, k8_dict)

In [4]:
k4_dict2, k5_dict2, k8_dict2 = shingle(filename2, k4_dict, k5_dict, k8_dict)

In [5]:
print(jaccard(k4_dict1, k4_dict2))
print(jaccard(k5_dict1, k5_dict2))
print(jaccard(k8_dict1, k8_dict2))

0.1509433962264151
0.13392857142857142
0.09349593495934959


In [6]:
hashs = []
rand_hash = random.sample(range(1, 991), 100)

for i in range(100):
    hashs.append(hash(rand_hash[i]))

In [7]:
for i in range(100):
    h = hashs[i]

In [8]:
def h1(x):
    return x % 5 + 1

def h2(x):
    return (2*x + 1) % 5 + 1

hashx = []
hashx.append(h1)
hashx.append(h2)

In [9]:
matris = np.zeros((5, 2))
matris_hash = np.zeros((5, 2))
signature_matrix = np.full((2, 2), 999)

matris[0, 0] = 1
matris[1, 1] = 1
matris[2, 0] = 1
matris[2, 1] = 1
matris[3, 0] = 1
matris[4, 1] = 1

In [ ]:
nrow = len(shingle_size)
ncol = len(filenames)
nhash = len(hashs)

# matris shingle var yok matrisi
matris = np.zeros((nrow, ncol))
matris_hash = np.zeros((nrow, nhash))
signature_matrix = np.full((nhash, nrow), 9999999)

In [10]:
for i in range(matris_hash.shape[0]):
    for j in range(matris_hash.shape[1]):
        h = hashx[j]
        matris_hash[i, j] = h(i + 1)
    
    for j in range(matris.shape[1]):
        if(matris[i, j] == 1):
            for k in range(matris_hash.shape[1]):
                if(signature_matrix[k, j] > matris_hash[i, k]):
                    signature_matrix[k, j] = matris_hash[i, k]
                    
                    
    print(signature_matrix)

print("matris hash")
print(matris_hash)
print("matris")
print(matris)
print("signature matrix")
print(signature_matrix)

[[  2 999]
 [  4 999]]
[[2 3]
 [4 1]]
[[2 3]
 [3 1]]
[[2 3]
 [3 1]]
[[2 1]
 [3 1]]
matris hash
[[ 2.  4.]
 [ 3.  1.]
 [ 4.  3.]
 [ 5.  5.]
 [ 1.  2.]]
matris
[[ 1.  0.]
 [ 0.  1.]
 [ 1.  1.]
 [ 1.  0.]
 [ 0.  1.]]
signature matrix
[[2 1]
 [3 1]]
